language: node_js
node_js:
  - 14.16.1
cache: npm

install:
  - npm install -g @angular/cli
  - npm install

script:
  - ng build

deploy:
  provider: pages
  skip_cleanup: true
  github_token: $GITHUB_TOKEN
  on:
    branch: gh-pages


