language: node_js
node_js:
  - 14
cache: npm

install:
  - npm install -g @angular/cli
  - npm install

script:
  - ng build --prod

deploy:
  provider: pages
  skip_cleanup: true
  github_token: $GITHUB_TOKEN
  keep_history: true
  on:
    branch: main


